
name: anahita.wtf
url: http://anahita.wtf
about: "<p>Hi, I'm <a href='/about'>anahita</a>.</p><p>I'm a small internet beastie that likes to program things and write about <a href='//sjwiki.org'>social justice</a>. </p>"
      
